"""Add ram and disk columns to node

Revision ID: 0004
Revises: 0003
Create Date: 2024-05-18 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('ram_total_mb', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('ram_used_mb', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('disk_total_mb', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('disk_used_mb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'disk_used_mb')
    op.drop_column('nodes', 'disk_total_mb')
    op.drop_column('nodes', 'ram_used_mb')
    op.drop_column('nodes', 'ram_total_mb')
    # ### end Alembic commands ###
