"""Add ram and disk columns to node

Revision ID: 5b4317f0e6ab
Revises: b20875908e2f
Create Date: 2025-05-05 22:45:10.871146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4317f0e6ab'
down_revision: Union[str, None] = 'b20875908e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('ram_total_mb', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('ram_used_mb', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('disk_total_mb', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('disk_used_mb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'disk_used_mb')
    op.drop_column('nodes', 'disk_total_mb')
    op.drop_column('nodes', 'ram_used_mb')
    op.drop_column('nodes', 'ram_total_mb')
    # ### end Alembic commands ###
